name: .NET

on:
  push:
    branches: [main, integrationTestMalmsteg]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore \Moneysystem\
        
      - name: Build
        run: dotnet build --no-restore \Moneysystem\
        
  
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore \TestSuite\
      - name: Build
        run: dotnet build --no-restore \TestSuite\
      - name: Test
        run: dotnet test --no-restore --no-build \TestSuite\

    
