name: .NET

on:
  push:
    branches: [main, integrationTestMalmsteg2]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore \Moneysystem\
        
      - name: Build
        run: dotnet build --no-restore \Moneysystem\
      - name: Install Entity Framework Core tools
        run: |
          cd Moneysystem
          dotnet tool install --global dotnet-ef --version 5.0
          dotnet add package Microsoft.EntityFrameworkCore.Design --version 5.0
      - name: Set up database
        run: |
          cd Moneysystem
          dotnet-ef migrations add Moneysystem --project Moneysystem.csproj
          dotnet-ef database update
      # - name: Update database
      #   run: dotnet-ef database update --project \Moneysystem\
  
        
  
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore \TestSuite\
      - name: Build
        run: dotnet build --no-restore \TestSuite\
      - name: Test
        run: dotnet test --no-restore --no-build \TestSuite\

    
